version: 2
updates:
  - package-ecosystem: pip
    labels:
      - dependencies
    directories:
      - /apps/
      - /backend/
      - /libs/
      - /tests/
      - /vscode/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    labels:
      - dependencies
    directories:
      - /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    labels:
      - CI/CD
      - dependencies
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    labels:
      - dependencies
    directories:
      - /apps/
      - /libs/
      - /omninexus/
      - /tests/
      - /vscode/
    schedule:
      interval: weekly
