sensor:
  interface:
    description: Main sensor monitoring interface.
    helpLink: network.html
    readonly: True
  mtu:
    description: Maximum Transmission Unit (MTU) of the sensor monitoring interface.
    helpLink: network.html
    readonly: True
  channels:
    description: Set the size of the nic channels. This is rarely changed from 1 
    helpLink: network.html
    forcedType: int
    node: True
    advanced: True
