# DAPR Pub/Sub Component: Firecrawl Events
# Event-driven communication for web scraping activities
# Topics:
#   - firecrawl.scrape.started - Scrape job started
#   - firecrawl.scrape.completed - Scrape job completed
#   - firecrawl.scrape.failed - Scrape job failed
#   - firecrawl.crawl.started - Crawl job started
#   - firecrawl.crawl.progress - Crawl job progress update
#   - firecrawl.crawl.completed - Crawl job completed
#   - firecrawl.crawl.failed - Crawl job failed
#   - firecrawl.extract.started - Extract job started
#   - firecrawl.extract.completed - Extract job completed
#   - firecrawl.extract.failed - Extract job failed
#   - firecrawl.document.cached - Document cached
#   - firecrawl.webhook.triggered - Webhook triggered

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-firecrawl
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: host
      value: "amqp://rabbitmq:5672"
    - name: consumerID
      value: "firecrawl-service"
    - name: durable
      value: "true"
    - name: deletedWhenUnused
      value: "false"
    - name: autoAck
      value: "false"
    - name: deliveryMode
      value: "2"  # Persistent messages
    - name: requeueInFailure
      value: "true"
    - name: prefetchCount
      value: "10"
    - name: reconnectWait
      value: "0"
    - name: concurrency
      value: parallel
    - name: exchangeKind
      value: "topic"
    - name: maxLen
      value: "10000"
    - name: maxLenBytes
      value: "104857600"  # 100MB
scopes:
  # Firecrawl services can publish/subscribe
  - firecrawl-api
  - firecrawl-worker
  - firecrawl-ui
  - playwright-service
  
  # Other services can subscribe to firecrawl events
  - ai-chat
  - ai-models
  - ai-training
  - ai-analytics
  - goose-server
  - goose-cli
  - n8n
  - fastapi
